##############################
### WINDOWS AND WORKSPACES ###
##############################

# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = match:class ^$, match:title ^$, match:xwayland true, match:float true, match:fullscreen false, match:pin false, no_focus on

# Blur wlogout
# layerrulev2 = ignorezero, namespace:logout_dialog
# Blur + ignore transparent pixels for wlogout (namespace: logout_dialog)
layerrule = blur on, ignore_alpha 1, match:namespace logout_dialog
